-- Shared narrative and chart. Progress and rewards are controlled by Campaign on the server.
local E = {}
E.Chapters = {
	{title="01 / KEEP THE LIGHT", objective="Restore E-01: at least 60 health and running power.", target="Generator", position=Vector3.new(-64,33,37),
		brief="You wake on KESTREL-9 after the evacuation alarm. A recording from engineer Mara Voss repeats one order: keep the lights alive. The crew left in a hurry. Their recorder is still in the new east archive.",
		reveal="E-01 is stable. The recorder in EAST LOGISTICS may explain why nobody came back.", reward=15},
	{title="02 / THE EMPTY ROSTER", objective="Recover the crew black box in EAST LOGISTICS.", target="CrewBlackbox",position=Vector3.new(176,33,28),
		brief="Mara recorded the evacuation count twice. The second count had one extra person. Search the crew archive across the east bridge.",
		reveal="BLACK BOX / MARA: We counted eight on the launch. Then nine. I locked the recorder here. The distress relay did not fail: someone disconnected it from the processing yard.",reward=20},
	{title="03 / A CUT WIRE", objective="Repair WEST RELAY: Electronics x3 + Copper x4.",target="WestRelay",position=Vector3.new(-164,33,28),cost={Electronics=3,Copper=4},
		brief="Restore the relay inside the processing workshop across the west bridge. Its governor also controls fuel delivery to E-01.",
		reveal="The cut was deliberate. A recovered weather packet leads to the offshore station. Governor restored: E-01 uses 15% less fuel for the rest of this run.",reward=25},
	{title="04 / THE FALSE STORM", objective="Take the boat to WEATHER STATION and recover its recording.",target="WeatherRecorder",position=Vector3.new(-1228,11,-908),
		brief="The company blamed a storm for the missing relief convoy. The weather station kept its own measurements. Pack fuel and provisions; use the station's low jetty to board.",
		reveal="WEATHER ARCHIVE: Winds calm at the time of the distress call. The storm warning was fabricated. A research ship, MV SILENCE, transmitted an evacuation cancellation under company authority.",reward=30},
	{title="05 / THE SILENCE ORDER", objective="Board MV SILENCE and retrieve its voyage recorder.",target="ShipRecorder",position=Vector3.new(1230,9,-778),
		brief="MV SILENCE lies northeast of the rig. Its cargo still has supplies. The bridge recorder contains the order that stranded the crew.",
		reveal="CAPTAIN'S RECORD: Halvard ordered the blackout to contain the organisms under KESTREL-9. Mara stayed behind to keep the lights running. Rescue vessel Aldmere is coming, but its navigator is receiving a false exclusion zone.",reward=35},
	{title="06 / THE TRUE COORDINATES", objective="Recover the override code from NORTH VAULT.",target="CompanyArchive",position=Vector3.new(192,11,-1528),
		brief="The northern archive holds the signed navigation override. Recover it, return to the rig, and transmit the evidence before the final rescue.",
		reveal="ARCHIVE / MARA: If you found this, you know. Send our coordinates, then send the recordings. Do not let them call us a weather accident. Override authenticated. Return to the north communications deck.",reward=40},
	{title="07 / LET THEM HEAR US", objective="At NORTH ARRAY: power LIGHTS + SONAR and defend a 45s transmission.",target="RescueTransmitter",position=Vector3.new(0,33,218),
		brief="The transmitter needs both navigation telemetry and a lit approach. Stay within 20 studs of the console while LIGHTS and SONAR are powered. Power loss or leaving the console pauses the upload. The signal attracts Climbers.",
		reveal="ALDMERE: Coordinates verified. We have your evidence, KESTREL-9. Keep that beacon alive. We will bring you home — and the world will hear what Halvard did.",reward=80,
		hold={seconds=45,powers={"Lights","Sonar"},radius=20,wave=3,label="UPLINK"}},
	{title="08 / THE THROAT", objective="Dive into THE THROAT and plant a sonar beacon: Electronics x2 + Copper x2 (Diving Gear required).",target="ThroatBeacon",position=Vector3.new(-450,-96,700),cost={Electronics=2,Copper=2},minDay=5,
		brief="Aldmere's sonar sees a trench opening west of the rig, right where the old pipeline ends. Mara called it the Throat. Research Diving Gear first: the bottom is at a hundred metres, and something warm is breathing down there.",
		reveal="BEACON ONLINE: The trench is a nest. Thousands of eggs line the walls, kept warm by heat leaking from KESTREL-9's drill string. The rig is not standing over the nest — it is feeding it.",reward=45},
	{title="09 / MARA'S LAST SHIFT", objective="Reach the DROWNED REFINERY far to the east and find Mara's recorder.",target="MaraRecorder",position=Vector3.new(3012,21,412),minDay=8,
		brief="Mara Voss's personal beacon still pings from the Drowned Refinery, three thousand metres east. It is a long run: upgrade the boat's tank at the dock and stop at the fuel relay buoys on the way.",
		reveal="MARA / FINAL ENTRY: I shut the heat exchangers here and the Throat went quiet for a week. Halvard reopened them from KESTREL-9. The last valve is in WELL CONTROL on the south-west deck. Close it and hold it closed. I am going into the water to cut the line myself. Keep the lights on for me.",reward=55},
	{title="10 / STARVE THE NEST", objective="In WELL CONTROL: power PUMPS + DEFENSE and hold the valve for 60 s.",target="WellValve",position=Vector3.new(-133,33,-221),minDay=11,
		brief="Close Mara's last valve. The pumps must flush the heat line while the defenses keep the deck clear. The nest will notice. Stay within 18 studs of the valve.",
		reveal="VALVE SEALED: The drill string cools. Sonar shows the Throat going dark. Climbers now come less often — but the Leviathan has lost its warmth too, and it is angry.",reward=70,
		hold={seconds=60,powers={"Pumps","Defense"},radius=18,wave=4,label="VALVE"}},
	{title="11 / HALVARD'S BARGE", objective="Board HALVARD'S BARGE in the far north-west and recover the containment codes.",target="ContainmentCodes",position=Vector3.new(-3196,9,2650),minDay=14,
		brief="Halvard ran the cover-up from a command barge anchored beyond the fog. His containment codes would prove the company knew — and could open the Throat again. The barge door needs a lock bypass: Electronics x4.",
		reveal="CONTAINMENT LOG / HALVARD: 'Seal the rig. Deny the survivors. The specimens are worth more than the crew.' Signed, dated, witnessed. Aldmere has everything now. All that is left is to be alive when they arrive.",reward=90},
}
E.Destinations={
	{name="KESTREL-9 / HOME",position=Vector3.new(-43,5,-74),note="Generator, crafting, north uplink and main boat dock."},
	{name="WEATHER STATION",position=Vector3.new(-1240,8,-920),note="Weather recorder, fuel and food. Use the low boarding jetty."},
	{name="MV SILENCE",position=Vector3.new(1220,6,-820),note="Research ship. Voyage recorder in the bridge; supplies on deck."},
	{name="NORTH VAULT",position=Vector3.new(180,8,-1540),note="Company archive and navigation override. Boarding jetty."},
	{name="RESCUE HARBOUR",position=Vector3.new(1260,8,920),note="Optional expedition stop: fuel, food, water and a crafting bench."},
	{name="REPEATER ISLAND",position=Vector3.new(-1080,8,1120),note="Optional resupply and crafting station on the western route."},
	{name="THE THROAT",position=Vector3.new(-450,2,700),note="Deep trench west of the rig. Diving Gear only. Crystals and the nest beacon."},
	{name="DROWNED REFINERY",position=Vector3.new(3000,8,330),note="Huge half-sunk refinery 3 km east. Mara's recorder, fuel, chemicals."},
	{name="SHIP GRAVEYARD",position=Vector3.new(-2600,4,-2480),note="Wrecks on a shoal to the south-west. Best scrap and electronics on the map."},
	{name="HALVARD'S BARGE",position=Vector3.new(-3200,8,2500),note="Command barge in the far north-west fog. Locked: Electronics x4."},
	{name="EAST RELAY BUOY",position=Vector3.new(1800,5,200),note="Fuel relay platform on the refinery route."},
	{name="SOUTH RELAY BUOY",position=Vector3.new(-1500,5,-1600),note="Fuel relay platform on the graveyard route."},
	{name="NORTH RELAY BUOY",position=Vector3.new(-1900,5,1850),note="Fuel relay platform on the barge route."},
	{name="GRAVE ISLAND",position=Vector3.new(-4400,4,-2280),note="Huge island far west. Old whaling station, hills to explore on foot, food and chemicals."},
	{name="RADAR ISLAND",position=Vector3.new(4600,4,-4150),note="South-east island with a dead radar station: electronics, copper, a lore log."},
	{name="NORTH ISLES",position=Vector3.new(800,4,4890),note="Three islands at the northern edge. Lighthouse keeper's camp and a crafting bench."},
	{name="KESTREL-8",position=Vector3.new(5200,2,2300),note="Sister rig abandoned 4.5 km east-north-east. Enormous loot, climb the long ladder."},
	{name="FAR EAST BUOY",position=Vector3.new(3800,5,-1200),note="Fuel relay on the Radar Island / KESTREL-8 routes."},
	{name="FAR WEST BUOY",position=Vector3.new(-3300,5,-1000),note="Fuel relay on the Grave Island route."},
	{name="FAR NORTH BUOY",position=Vector3.new(700,5,3300),note="Fuel relay on the North Isles route."},
}
return E
